# 📊 Sentiment Analysis Experimentation

This notebook demonstrates:
- Data exploration
- Text preprocessing
- Feature extraction using TF-IDF
- Model comparison
- Final model selection

In [1]:
import pandas as pd
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\11vai\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("../data/raw/sample_raw.csv")
df.head()

                          text sentiment
0          I love this product  positive
1           Amazing experience  positive
2  Very happy with the service  positive
3        This is the worst app  negative
4          Terrible experience  negative

In [3]:
def clean_text(text):
    text = re.sub(r"http\S+|[^A-Za-z\s]", "", str(text))
    text = text.lower()
    text = " ".join([w for w in text.split() if w not in stopwords.words('english')])
    return text

df['clean_text'] = df['text'].apply(clean_text)
df.head()

                          text sentiment           clean_text
0          I love this product  positive         love product
1           Amazing experience  positive   amazing experience
2  Very happy with the service  positive        happy service
3        This is the worst app  negative            worst app
4          Terrible experience  negative  terrible experience

In [4]:
X = df['clean_text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [6]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Naive Bayes": MultinomialNB(),
    "Random Forest": RandomForestClassifier(n_estimators=200)
}

for name, model in models.items():
    model.fit(X_train_vec, y_train)
    pred = model.predict(X_test_vec)
    acc = accuracy_score(y_test, pred)
    print(name, "Accuracy:", acc)

Logistic Regression Accuracy: 0.0
Naive Bayes Accuracy: 0.3333333333333333
Random Forest Accuracy: 0.3333333333333333

In [7]:
model = RandomForestClassifier(n_estimators=200)
model.fit(X_train_vec, y_train)

pred = model.predict(X_test_vec)

print("Final Model Accuracy:", accuracy_score(y_test, pred))

Final Model Accuracy: 0.0

# ✅ Conclusion

- Tested multiple models
- Random Forest performed better
- TF-IDF helped convert text into useful features

👉 Final model used in dashboard: Random Forest